version: "3"
services:
  app:
    image: 'jc21/nginx-proxy-manager:latest'
    restart: unless-stopped
    ports:
      # These ports are in format <host-port>:<container-port>
      - '81:80' # Public HTTP Port
      - '444:443' # Public HTTPS Port
      - '82:81' # Admin Web Port

    # network_mode: host
    # extra_hosts:
    # - "host.docker.internal:host-gateway"

    volumes:
      - ./data:/data
      - ./letsencrypt:/etc/letsencrypt